# Server Configuration
server:
  port: ${CONTAINER_PORT:8080}
  error:
    path: ${ERROR_PATH}
    whitelabel:
      enabled: ${WHITELABEL_ENABLED}

# Frontend Configuration
ui:
  app:
    url: ${UI_APP_URL}

# Spring Profiles
spring:
  profiles:
    active: ${ACTIVE_PROFILE:dev}

  # Servlet Configuration
  servlet:
    multipart:
      max-file-size: ${MAX_MULTIPART_FILE_SIZE}
      max-request-size: ${MAX_MULTIPART_REQUEST_SIZE}

  # Datasource Configuration
  datasource:
    url: jdbc:${POSTGRESQL}://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?currentSchema=${POSTGRES_CURRENT_SCHEMA}
    name: ${POSTGRES_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  # JPA Configuration
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO}
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: EET

  # SQL Initialization
  sql:
    init:
      mode: ${SQL_INIT_MODE}

  # Mail Configuration
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          writetimeout: ${MAIL_WRITE_TIMEOUT}
          connectiontimeout: ${MAIL_CONN_TIMEOUT}
          timeout: ${MAIL_TIMEOUT}
          auth: ${MAIL_AUTH_ENABLED}
          starttls:
            enable: ${TLS_ENABLED}
            required: ${TLS_REQUIRED}
      verify:
        host: ${VERIFY_EMAIL_HOST}

# Scheduled Jobs Configuration
scheduled-jobs:
  inactivity_email_cron: ${INACTIVITY_EMAIL_CRON}

# Application Configuration
application:
  title: ${APP_TITLE}
  version: ${APP_VERSION}
  domain: ${APP_DOMAIN}
  administration: ${APP_ADMINISTRATION}

# SMS Verification Configuration
mfa:
  sms:
    from: ${FROM_NUMBER_RO}
    sid-key: ${SID_KEY}
    token-key: ${SMS_TOKEN_KEY}

# JWT Configuration
jwt:
  secret: ${JWT_SECRET}
